#!/usr/bin/env python3
"""Pack the data/*.json files into data/bundle.js.

The calculator, the comparison tables and the Services cards read their data with
fetch(). Browsers refuse fetch() for files opened straight from a folder
(file:///…/index.html), which is how a friend who downloads the repo will open it,
and the pages then show empty. site.js therefore falls back to this bundle, but
only on file://: online it is never downloaded.

    python3 tools/bundle_data.py

tools/stamp.py runs it for you, so it stays in step with the JSON files.
"""

import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "bundle.js")


def build():
    data = {}
    for path in sorted(glob.glob(os.path.join(ROOT, "data", "*.json"))):
        with open(path, encoding="utf-8") as f:
            data[os.path.basename(path)] = json.load(f)
    body = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    text = ("/* Generated by tools/bundle_data.py from data/*.json. Do not edit by hand.\n"
            "   Only used when a page is opened from a folder (file://); see site.js. */\n"
            "window.SH_DATA_BUNDLE=" + body + ";\n")
    old = None
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as f:
            old = f.read()
    if text != old:
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(text)
        print("data/bundle.js updated (%d files, %d KB)" % (len(data), len(text) // 1024))
    return text != old


if __name__ == "__main__":
    build()
