#!/usr/bin/env python3
"""Write the canonical link, Open Graph and Twitter tags into every page.

Social scrapers (Telegram, Facebook, WhatsApp, X) do not run JavaScript, so
these tags have to be real HTML rather than something site.js injects. This
script is the one place that knows the site's address: change BASE_URL below,
run

    python3 tools/seo.py

from the project root, and every page is rewritten. It also regenerates
sitemap.xml and robots.txt.

The script only ever replaces the block between the two SEO markers, so
anything else in <head> is left alone and it is safe to run repeatedly.
"""

import os
import re
import html
from datetime import date

# ---------------------------------------------------------------- CONFIG
# Where the site is published. Change this one line when the domain changes.
# The default is the GitHub Pages address for github.com/sayfievjasurbek/studyhouse.
BASE_URL = "https://sayfievjasurbek.github.io/studyhouse"

SITE_NAME = "Study House"
OG_IMAGE = "images/og-card.jpg"          # 1200x630
DEFAULT_LOCALE = "uz_UZ"                 # the site opens in Uzbek
ALT_LOCALES = ["ru_RU", "en_US"]

START = "  <!-- SEO: generated by tools/seo.py — do not edit by hand -->"
END = "  <!-- /SEO -->"

# Page -> how often it changes, and how important it is relative to the rest.
PRIORITY = {
    "index.html": ("weekly", "1.0"),
    "services/index.html": ("monthly", "0.9"),
    "destinations/index.html": ("monthly", "0.9"),
    "gpa-calculator/index.html": ("monthly", "0.8"),
    "expertise/index.html": ("monthly", "0.7"),
}
DEFAULT_PRIORITY = ("monthly", "0.6")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def pages():
    out = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in (".git", "tools", "images", "data")]
        for name in filenames:
            if not name.endswith(".html") or name.startswith("_"):
                continue
            rel = os.path.relpath(os.path.join(dirpath, name), ROOT)
            out.append(rel.replace(os.sep, "/"))
    return sorted(out)


def canonical_for(rel):
    """A directory index is addressed by its directory, not by index.html."""
    if rel == "index.html":
        return BASE_URL + "/"
    if rel.endswith("/index.html"):
        return BASE_URL + "/" + rel[: -len("index.html")]
    return BASE_URL + "/" + rel


def meta_of(source, name, attr="name"):
    m = re.search(r'<meta\s+%s="%s"\s+content="([^"]*)"' % (attr, re.escape(name)), source)
    return m.group(1) if m else ""


def block_for(rel, source):
    url = canonical_for(rel)
    title = re.search(r"<title>(.*?)</title>", source, re.S)
    title = html.unescape(title.group(1).strip()) if title else SITE_NAME
    desc = html.unescape(meta_of(source, "description"))
    is_home = rel == "index.html"

    lines = [
        START,
        '  <link rel="canonical" href="%s">' % url,
        '  <meta property="og:type" content="%s">' % ("website" if is_home else "article"),
        '  <meta property="og:site_name" content="%s">' % SITE_NAME,
        '  <meta property="og:url" content="%s">' % url,
        '  <meta property="og:title" content="%s">' % html.escape(title, quote=True),
        '  <meta property="og:description" content="%s">' % html.escape(desc, quote=True),
        '  <meta property="og:image" content="%s/%s">' % (BASE_URL, OG_IMAGE),
        '  <meta property="og:image:width" content="1200">',
        '  <meta property="og:image:height" content="630">',
        '  <meta property="og:locale" content="%s">' % DEFAULT_LOCALE,
    ]
    lines += ['  <meta property="og:locale:alternate" content="%s">' % loc for loc in ALT_LOCALES]
    lines += [
        '  <meta name="twitter:card" content="summary_large_image">',
        '  <meta name="twitter:title" content="%s">' % html.escape(title, quote=True),
        '  <meta name="twitter:description" content="%s">' % html.escape(desc, quote=True),
        '  <meta name="twitter:image" content="%s/%s">' % (BASE_URL, OG_IMAGE),
        END,
    ]
    return "\n".join(lines)


def apply_to(rel):
    path = os.path.join(ROOT, rel)
    source = open(path, encoding="utf-8").read()
    block = block_for(rel, source)

    if START in source:
        source = re.sub(re.escape(START) + r".*?" + re.escape(END), block, source, flags=re.S)
    else:
        # Straight after the favicon, which is the last <link> in every head here.
        anchor = re.search(r'\n(  <link rel="icon"[^>]*>)\n', source)
        if not anchor:
            anchor = re.search(r"\n(  </head>)", source)
            source = source[: anchor.start()] + "\n" + block + source[anchor.start():]
        else:
            source = source[: anchor.end(1)] + "\n" + block + source[anchor.end(1):]

    open(path, "w", encoding="utf-8").write(source)


def write_sitemap(rels):
    today = date.today().isoformat()
    rows = []
    for rel in rels:
        freq, prio = PRIORITY.get(rel, DEFAULT_PRIORITY)
        rows.append(
            "  <url>\n"
            "    <loc>%s</loc>\n"
            "    <lastmod>%s</lastmod>\n"
            "    <changefreq>%s</changefreq>\n"
            "    <priority>%s</priority>\n"
            "  </url>" % (canonical_for(rel), today, freq, prio)
        )
    open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8").write(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(rows)
        + "\n</urlset>\n"
    )


def write_robots():
    open(os.path.join(ROOT, "robots.txt"), "w", encoding="utf-8").write(
        "User-agent: *\n"
        "Allow: /\n"
        "\n"
        "Sitemap: %s/sitemap.xml\n" % BASE_URL
    )


if __name__ == "__main__":
    rels = pages()
    for rel in rels:
        apply_to(rel)
    write_sitemap(rels)
    write_robots()
    print("%d pages updated, sitemap.xml and robots.txt written for %s" % (len(rels), BASE_URL))
